### ISSUE TITLE
[BUG] Test TestStreamCompression.testPagedStreams fails

### ISSUE THREAD

**Issue by yurivict** [AcademySoftwareFoundation/openvdb#1103]
### Environment
**Operating System:** FreeBSD 13
**Version:** / Commit SHA: 8.1.0
**Other:** clang-11

### Describe the bug
```

[ RUN      ] TestStreamCompression.testPagedStreams
/disk-samsung/freebsd-ports/misc/openvdb/work/openvdb-8.1.0/openvdb/openvdb/unittest/TestStreamCompression.cc:422: Failure
Expected equality of these values:
  ss.tellp()
    Which is: 4452
  std::streampos(5400)
    Which is: 5400
/disk-samsung/freebsd-ports/misc/openvdb/work/openvdb-8.1.0/openvdb/openvdb/unittest/TestStreamCompression.cc:455: Failure
Expected equality of these values:
  ss.tellg()
    Which is: 4452
  std::streampos(5400)
    Which is: 5400
/disk-samsung/freebsd-ports/misc/openvdb/work/openvdb-8.1.0/openvdb/openvdb/unittest/TestStreamCompression.cc:548: Failure
Expected equality of these values:
  fileout.tellp()
    Which is: 42724
  std::streampos(51480)
    Which is: 51480
[  FAILED  ] TestStreamCompression.testPagedStreams (35 ms)
```

**Comment by danrbailey** [comment]
I think this error likely means that you're using a version of Blosc that we don't officially support (we recommend 1.5.0)? If you'd like to submit a patch to either update these values for FreeBSD or for a later version of Blosc, we'd gladly accept.

**Comment by yurivict** [comment]
I use c-blosc-1.21.0 from FreeBSD ports.

Repology shows  that  c-blosc-1.5.0 isn't used anywhere any more: https://repology.org/project/c-blosc/versions

It seems to be a very old version. Github shows (https://github.com/Blosc/c-blosc) that blosc-1.5 was released in 2014.

**Comment by Idclip** [comment]
@yurivict yeah this is a problem - VDB is locked to blosc 1.5.0  mainly due to incompatibility issues between various blosc versions: https://www.blosc.org/posts/new-forward-compat-policy/

The short of it is that we really need to investigate which version of blosc we can switch to safely without breaking the reader for files compressed with 1.5.0. On top of that, as you point out in this issue, newer versions of blosc are changing the compression ratios so we really need to check that these changes are legitimate. We need to come up with a compatible subset of blosc versions and fix the tests accordingly, but we need to be careful with this!

**Comment by Idclip** [comment]
Just a note that as of OpenVDB 9 we've bumped our new proposed blosc minimum to 1.17.0. 1.17.0 and 1.18.0 pass our unit tests. I still get test failures with 1.19.0, 1.20.0 and 1.21.0 so this issue is still valid.
