### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by utilitydelta** [AcademySoftwareFoundation/openvdb#1108]
### Environment
**Operating System:** Windows 10
**Version / Commit SHA:** 8.1.0
**Other:** MSVC / VS 2019

### Describe the bug
I'm trying this example code here:
https://academysoftwarefoundation.github.io/openvdb/codeExamples.html#sAllocatingGrids

It fails on 'insertMeta("radius"....' when in debug mode, i'm running x64. 
Microsoft C++ exception: std::bad_alloc at memory location 0x000000BEBDBFF310.

If I run in release it works. Is there something simple I am missing?

### To Reproduce
1. New VS 2019 blank cpp project
2. Copy paste the code from tutorial link 'Creating and writing a grid'
3. Run in debug with x64

### Expected behavior
Should run to end

### Additional context
Sorry if I did something noob; been a while since I did C++ :)

**Comment by Idclip** [comment]
@utilitydelta in my experience this is typically because you've linked against libs which have not been compiled against the appropriate CRT i.e. your app is set to Debug where as `openvdb.lib` or subsequent deps have been built in Release. Make sure your project is configured correctly such that you're picking up debug library variants in Debug builds

**Comment by Idclip** [comment]
Closing, feel free to reopen if this is still an issue!
