### ISSUE TITLE
[BUG] memUsage() doesn't return the right value unless the grid has been already parsed

### ISSUE THREAD

**Issue by thilamb** [AcademySoftwareFoundation/openvdb#1305]
### Environment
**Operating System:**Windows10, 64bits
**Version / Commit SHA:** VDB 8.1.1
**Other:** C++ standard etc., vcpkg

### Describe the bug
Gird::memUsage (which calls Tree:memUsage) doesn't return the correct value, unless the grid/tree has been parsed before.

### To Reproduce
1. Build OpenVDB
2. run "vdb_print" on a large VDB file (e.g WDAS cloud) -> you get the wrong result
3. run "vdb_print -l" on the same large VDB file -> you get the correct value

```
vdb_print.exe wdas_cloud.vdb
density      float (-1041,-324,-1429)->(945,1026,1019) 1987x1351x2449  1.49GVox  302MB
```
versus

```
vdb_print.exe -l wdas_cloud.vdb
...
Memory footprint:
  **Actual:                3.817 GB**
  Active leaf voxels:    3.193 GB
  Dense equivalent:     24.491 GB
  Actual footprint is 15.6% of an equivalent dense volume
  Leaf voxel footprint is 83.7% of actual footprint
...
```

### Expected behavior
I expect memUsage to return the correct memory size used for any grid. Parsing an entire VDB file before being able to return the correct memory size is not acceptable (e.g, using vdb_print -l on WDAS cloud takes several minutes)

Thanks !

**Comment by thilamb** [comment]
FYI, the wdas_cloud.vdb file is 2 861 156 Ko

**Comment by Idclip** [comment]
Thanks @thilamb.

I haven't tested this, but I assume this is due to delayed loading. The function that's being invoked here in both cases `Grid::memUsage()`. In the first case (without specifying `-l`) the value buffers of the VDB aren't loaded into memory, causing `Grid::memUsage()` to report a lower number, representative of the tree topology memory cost.

This isn't technically a bug (this is the correct behaviour of `Grid::memUsage()`), but I 100% agree the way `vdb_print` displays this information is wrong. There's two things we should do:

1) Make sure the memory printed is annotated with something like "out of core" or "topology"  if delay loading is enabled.
2) Potentially update `Grid::memUsage()` to take a flag which forces it to calculate the potentially total memory usage even if the grid is delay loaded. This wouldn't need to load the value buffers from disk as we should be able to compute this based on the tree topology and it's value type alone.

**Comment by thilamb** [comment]
That sounds great, thank you !

To give you a bit of context, I spotted this "issue" because I'm using memUsage to show the memory foortprint to users when selecting an OpenVDB file, but then noticed severe discrepancies with the real values.

Looking forward to your changes.

Cheers
