### ISSUE TITLE
[BUG] VDBs culled after a certain distance

### ISSUE THREAD

**Issue by philTunni** [AcademySoftwareFoundation/openvdb#1359]
### Environment
**Operating System:** (Windows 10 Pro)
**Version / Commit SHA:** (commit version eb5de021bfed434322c33f2e51ec3aa187867385)

### Describe the bug
When a vdb has been added to unreal 5, after a certain range it will be culled off. 

I had a look at what controls this but there doesn't seem to be a way to control this. Is this functionality possible or need to be added?

### To Reproduce
Steps to reproduce the behaviour:
1. Open UE5 and add vdb into any scene
2. Move camera away from vdb
3. You will see the vdb fade after a certain distance

### Expected behaviour
I expected that it would be visible at further distances, especially as I was working on cloud landscape looks and after certain ranges its no longer visible

**Comment by Idclip** [comment]
Hi @philTunni, we don't maintain any plugins for Unreal. You'll be better off filing an issue with whatever plugin you're using to import vdb files or Unreal directly if they have native support for this.

**Comment by philTunni** [comment]
I did contact Thibault (who made the plugin) and from their investigation they pointed me here:

"I've been able to reproduce the issue and it is not Unreal related. It is an issue with NanoVDB indeed. Sadly, there isn't much I can do about it. I recommend posting an issue on their github"

**Comment by Idclip** [comment]
I see - unfortunately as we don't have any knowladge of how VDB has been integrated into this plugin we can't assist without more info. However it sounds like the creator of the plugin has identified the issue in NanoVDB which is causing the problem? If they were able to get in touch and describe the issue that could help - we can look to address anything on the VDB side but anything specific to UE or UE glue code would have to be fixed by the plugin maintainer.

**Comment by Idclip** [comment]
Closing, but please feel free to create a new issue if the creator is able to provide more information.
