### ISSUE TITLE
[QUESTION] Does NanoVDB support frames / animation

### ISSUE THREAD

**Issue by Carandiru0** [AcademySoftwareFoundation/openvdb#1369]
### Environment
**Operating System:** Windows 10
**Version / Commit SHA:** 9.0
**Other:** Visual Studio 2022, Custom Vulkan micro-voxel Engine

### Question?

Can I load a open vdb file (eg.) embergen free vdbs, convert each frame to a nanovdb then cycle thru the "frames" / "volumes" of nvdb's to display ?

Or is there a better way? Knowning the nanovdb volume is static, perhaps multiple static volumes would be a good workaround for this proposed usage?

I ask this question only because the documentation doesn't clarify (for me at least) if this is possible.

Thanks!
Jason

**Comment by gaida-exe** [comment]
Hey, for questions, you should post in the discussions tab right next to the pull requests. The maintainers or the community answer there the questions regarding Open/NanoVDB.

This is for PNanoVDB, since I don't have any experience with Nano directly.
As far as I know, PNano does not support cycling through volumes, you would, like you suggested, have multiple buffers in the shader or change the buffer via a descriptor set/table.

**Comment by Carandiru0** [comment]
ah thank you, was not aware of the discussions tab - sorry.
