### ISSUE TITLE
Best practice to populate a grid with large number of points

### ISSUE THREAD

**Issue by bravobohan** [AcademySoftwareFoundation/openvdb#430]
What is the best practice to populate the grid with large number of 3D points? Currently I am using a `for` loop and using `Grid.getAccessor()->setValue(openvdb::Coord, valueType)`; I am wondering if there is a better and faster way to achieve it.

**Comment by kmuseth** [comment]
As you’ve noted there are several ways to set values in a VDB grid, and unfortunately the one you describe is arguably the slowest :) Here’s a quick explanation:

Tree::setValue performs a traditional (top-down) tree travel whereas ValueAccessor::setValue performs a much faster inverted tree (button-up) traversal. However, a ValueAccessor achieves it’s superior performance by mean of caching which implies two things. 1) it’s not thread-safe (so use one per thread) and more relevant to your question 2) it should always be re-used for more than once (for caching to make sense). When use do grid.getAccessor()->setValue you temporarily construct a ValueAccessor that is only used once. This is slower then even grid.tree().setValue! The best performance is achieved if you do “auto acc = grid.getAccessor()” once (per thread) and the do acc.setValue for all your insertions. Hope this makes sense!?

Cheers,
Ken

**Comment by asherikov** [comment]
1. I wonder if caching implies delays in actual grid updates. Is there some sort of a sync, e.g., on destruction?
2. It appears that performance of accessor depends on spatial localization of updates, and in some cases may be inferior to updates with `grid.tree()`. Is that so?
Thanks.

**Comment by bravobohan** [comment]
> As you’ve noted there are several ways to set values in a VDB grid, and unfortunately the one you describe is arguably the slowest :) Here’s a quick explanation: Tree::setValue performs a traditional (top-down) tree travel whereas ValueAccessor::setValue performs a much faster inverted tree (button-up) traversal. However, a ValueAccessor achieves it’s superior performance by mean of caching which implies two things. 1) it’s not thread-safe (so use one per thread) and more relevant to your question 2) it should always be re-used for more than once (for caching to make sense). When use do grid.getAccessor()->setValue you temporarily construct a ValueAccessor that is only used once. This is slower then even grid.tree().setValue! The best performance is achieved if you do “auto acc = grid.getAccessor()” once (per thread) and the do acc.setValue for all your insertions. Hope this makes sense!? Cheers, Ken
> […](#)

Got it! Awesome! Thank you for the explanation. :)

**Comment by kmuseth** [comment]
Hi Alexander,

1) Sorry, I should have clarified exactly what I meant to "caching". It's
not caching the actual values that you're inserting, but rather the access
pattern (specifically tree nodes). This means values are in fact inserted
immediately (the the function call to ValueAccessor::setValue returns) and
no sync is required.

2) The only time I would advice using Tree::setValue over
ValueAccessor::setValue is when (for some strange reason) you cannot re-use
the accessor more than once (typically because of limitations on client
code). You're right that in rare situations the buttom-up transversal with
cached nodes might end up performing a full top-down traversal which will
of course make is slower than Tree::setValue, but it's rare (since child
nodes of the root are gigantic - 4096^3) and on average the ValueAccessor
will out-perform it because it almost always avoids going through the root
note (which is the slowest node to access). However, the actual performance
difference between the two approaches has to be compared to all the other
operation you perform, so in its likely that in many practical applications
it doesn't actually matter which one of the two you end up using :)
Profiling is really the only to tell but I'd be surprised if it showed
Tree::setValue to be the fastest.

Cheers,
Ken

**Comment by asherikov** [comment]
@kmuseth , very informative, thank you.
