### ISSUE TITLE
Windows build instructions don't work

### ISSUE THREAD

**Issue by scaredyfish** [AcademySoftwareFoundation/openvdb#495]
I was following the Windows build instructions at https://github.com/AcademySoftwareFoundation/openvdb

I experienced the same error as in #429 which I resolved using the advice in that ticket.

Also, I ultimately built it from the Visual Studio IDE, as make is not part of my Windows toolchain. 

Could the build instructions please be updated?

**Comment by danrbailey** [comment]
We're happy to make some changes to the build instructions.

@scaredyfish @Danielhu229 - would one of you be willing to highlight exactly what needs changing? We'd prefer to keep the cmake command as short as possible when using vcpkg rather than recommending a bunch of explicit -D*_ROOT overrides as @Idclip commented in #429. (Our Windows CI could use the same improvements to be honest).

**Comment by Idclip** [comment]
It may be that using `NO_DEFAULT_PATH` within our `find_xxx()` commands is causing issues when providing a toolchain file. TBH I don't think we should be manually specifying system paths within the root CMakeLists.txt, we should let CMake do its thing with the option to only use explicit searching if necessary. I have a branch here which shows what I mean:

https://github.com/Idclip/openvdb/tree/cmake_no_default_path

I'm also unable to test this, might put in a draft PR to see what azure does with these changes unless getting azure working on our custom forks is a thing? Regardless, I think we should improve the README to clarify that those instructions are only a starting point

**Comment by nranthony** [comment]
Hi,
I'm also experiencing troubles with building on Win10.  I received the same errors as in #429, and have been banging my head on understanding why for a while.

I used CMake GUI to configure the package and got the same error as using the command line `cmake -DCMAKE_TOOLCHAIN_FILE=C:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake ..`.  I then pointed CMake (GUI), manually updating the path in the Value column, to the IlmBase_Half_DLL and IlmBase_Half_LIBRARY in `C:\dev\vcpkg\installed\x64-windows\bin` and `C:\dev\vcpkg\installed\x64-windows\lib` respectively.  I used files `Half-2_3.dll` and `Half-2_3.lib`.

I could not figure out how to make the changes suggested in the links in https://github.com/AcademySoftwareFoundation/openvdb/issues/429#issuecomment-491520418 and tried a modified version of the example CMake command:
`cmake -G"Visual Studio 15 2017 Win64" -DCMAKE_CONFIGURATION_TYPES=%CONFIGURATION% -DCMAKE_INSTALL_PREFIX=%APPVEYOR_BUILD_FOLDER%\install -DCMAKE_TOOLCHAIN_FILE=C:\dev\vcpkg\scripts\buildsystems\vcpkg.cmake -DOPENVDB_ABI_VERSION_NUMBER=6 -DOPENVDB_BUILD_BINARIES=OFF -DOPENVDB_BUILD_PYTHON_MODULE=ON -DOPENVDB_BUILD_UNITTESTS=ON -DOPENEXR_ROOT=C:\dev\vcpkg\installed\x64-windows -DILMBASE_ROOT=C:\dev\vcpkg\installed\x64-windows -DTBB_ROOT=C:\dev\vcpkg\installed\x64-windows -DBLOSC_ROOT=C:\dev\vcpkg\installed\x64-windows -DUSE_BLOSC=ON -DCPPUNIT_ROOT=C:\dev\vcpkg\installed\x64-windows -DBOOST_ROOT=C:\dev\boost_1_71_0 -DBOOST_LIBRARYDIR=C:\dev\boost_1_71_0\lib ..
`

I also tried manually adding the Ilm_Base_ROOT and Ilm_Base_INLCUDE_DIR folders but still go errors on configuring the the build files.

Any pointers would be much appreciated.
Thanks

**Comment by Idclip** [comment]
Hi @nranthony, sorry you're running into issues. 

> I also tried manually adding the Ilm_Base_ROOT and Ilm_Base_INLCUDE_DIR folders but still go errors on configuring the the build files.

I assume you've installed all dependencies using `vcpkg install`? Can you attach the CMake output you're getting with your latest attempts? Thanks.

**Comment by nranthony** [comment]
Using CMake 3.14.5 GUI, with source as `C:/dev/openvdb` and build as `C:/dev/openvdb/build`, I get the [CMakeOutput_asis.log](https://github.com/AcademySoftwareFoundation/openvdb/files/3633736/CMakeOutput_asis.log)
I tried to then manually edit the dll and lib that it can't find:
![image](https://user-images.githubusercontent.com/16306836/65290637-120f3880-db1e-11e9-9165-3961cf09ba7c.png)
and it would appear that on hitting Configure it doesn't create a fresh CMakeOutput.log, but I see the same error.

I then tried to follow the suggestion here https://www.openvdb.org/documentation/doxygen/build.html#buildDependencies to add the `XXX_INCLUDEDIR / XXX_LIBRARYDIR` by clicking Add Entry and defining the paths `C:/dev/vcpkg/installed/x86-windows/lib` and `C:/dev/vcpkg/installed/x86-windows/lib` with an empty cache and then hitting Configure
![image](https://user-images.githubusercontent.com/16306836/65291102-edb45b80-db1f-11e9-8313-482289696374.png)
but get the same error [CMakeOutput_xxx_paths.log](https://github.com/AcademySoftwareFoundation/openvdb/files/3633740/CMakeOutput_xxx_paths.log)
On looking through the the cmake files I notice that there aren't variable called `XXX_INCLUDEDIR / XXX_LIBRARYDIR`, but instead see `XXX_INCLUDE_DIRS / XXX_LIBRARY_DIRS`, but get the same error.
![image](https://user-images.githubusercontent.com/16306836/65291400-328cc200-db21-11e9-97dd-9177c7e9c652.png)

I then tried the `SYSTEM_LIBRARY_PATHS` option, but losing faith in changing the parameters in CMake GUI I went to the cmake files.  I added a few lines to CMakeLists.txt in the `C:\dev\opendvdb`:
```
# System path configuration

if(USE_SYSTEM_LIBRARY_PATHS)
  set(SYSTEM_LIBRARY_PATHS
    ~/Library/Frameworks
    /Library/Frameworks
    /usr/local
    /usr
    /sw  # Fink
    /opt/local  # DarwinPorts
    /opt/csw  # Blastwave
    /opt
    "C:/dev/vcpkg/installed/x86-windows/"
    "C:/dev/vcpkg/installed/x86-windows/bin"
  )
endif()
```
and this is the most success I've had, as I can pass the IlmBase errors, but then faced boost and python errors, see [CMakeOutput_sysPath.log](https://github.com/AcademySoftwareFoundation/openvdb/files/3633765/CMakeOutput_sysPath.log)

I then tried to add a few different options for the boost folder into the above set command, without success.  I cloned the boost folder directly and tried those folders, but no joy.  I installed python 2 using the direct download from https://www.python.org/downloads/ and installed on the C: drive, but that didn't help the python error (Note, I have python 3 via Anaconda).

At this point I stop adding CMakeOutput.log files as this surely is the wrong route.  Any help you can offer is greatly appreciated.  Thanks

**Comment by Idclip** [comment]
Hi @nranthony, thanks for all the info and your debug attempts! I think there are two separate problems here. The first is, as you've identified, an issue with how  the `SYSTEM_LIBRARY_PATHS` variable is being used on Windows (similar to OPs problem). The second is potentially not exclusive to windows and is to do with our current CMake support for newer versions of boost and python (specifically Boost >1.66 and Python >=3). To help diagnose this a bit further I'm going to need the CMake commands you're running and the CMake terminal output, not the CMakeOutput.log files. The two terminal outputs that would be most useful are the output to one of your first attempts here:

> I could not figure out how to make the changes suggested in the links in #429 (comment) and tried a modified version of the example CMake command:
cmake -G"Visual Studio 15 2017 Win64" -DCMAKE_CONFIGURATION_TYPES=%CONFIGURATION% -DCMAKE_INSTALL_PREFIX=%APPVEYOR_BUILD_FOLDER%\install -DCMAKE_TOOLCHAIN_FILE=C:\dev\vcpkg\scripts\buildsystems\vcpkg.cmake -DOPENVDB_ABI_VERSION_NUMBER=6 -DOPENVDB_BUILD_BINARIES=OFF -DOPENVDB_BUILD_PYTHON_MODULE=ON -DOPENVDB_BUILD_UNITTESTS=ON -DOPENEXR_ROOT=C:\dev\vcpkg\installed\x64-windows -DILMBASE_ROOT=C:\dev\vcpkg\installed\x64-windows -DTBB_ROOT=C:\dev\vcpkg\installed\x64-windows -DBLOSC_ROOT=C:\dev\vcpkg\installed\x64-windows -DUSE_BLOSC=ON -DCPPUNIT_ROOT=C:\dev\vcpkg\installed\x64-windows -DBOOST_ROOT=C:\dev\boost_1_71_0 -DBOOST_LIBRARYDIR=C:\dev\boost_1_71_0\lib ..

and the output to your last modified `SYSTEM_LIBRARY_PATHS` where you ran into the boost/python issues. If possible, running these commands with a fresh build directory would also be helpful.

Note that there's a number of PRs which attempt to address these issues which are still in review/pending some more investigation (#504 and #503) so any feedback you can provide would help steer these.

**Comment by nranthony** [comment]
Hi @Idclip thanks for the follow up.

I decided to start fresh.  I deleted my entire dev folder and started over.  I downloaded vcpkg and followed the instructions (strangely ran into a git error I've not seen before, and instead downloaded directly).  My workflow for your reference is here:  [workflow.txt](https://github.com/AcademySoftwareFoundation/openvdb/files/3639102/workflow.txt)

I realized that I should probably use x86 for everything in the modified cmd line version, given `cmake -DCMAKE_TOOLCHAIN_FILE=c:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake ..` uses x86.  It then turned out that I didn't need to edit the CMakeLists.txt file to get to the same endpoint as above, so there's a little progress I guess.

I think the boost troubles might have also been overcome, but alas I still run into errors in the `Configuring OpenVDBPython` section.  I've collated the two distinct cmake cmds and outputs here:  [cmake cmd output.txt](https://github.com/AcademySoftwareFoundation/openvdb/files/3639104/cmake.cmd.output.txt)

I then tried to add a few python flags, as can be seen in the workflow text, but it didn't change the error.

I hope this is helpful.  Please let me know if you'd like me to try anything differently on my next attempts.  Thanks in advance for your time.

**Comment by Idclip** [comment]
Hi @nranthony, thanks for all the feedback.

r.e. the git command, afaik, this is because git@ is an shh protocol (i.e. ssh://git@) - so unless you have correct keys, that won't work. The following should be okay:
`git clone https://github.com/AcademySoftwareFoundation/openvdb.git`

> It then turned out that I didn't need to edit the CMakeLists.txt file to get to the same endpoint as above, so there's a little progress I guess.

That's great. You obviously shouldn't need to manually specify every dep path, this is a bug which #504 will address (so you'll be able to run `cmake -DCMAKE_TOOLCHAIN_FILE=c:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake ..`). However there's a bit more investigation that needs to be done regarding later version of cmake and how we're using the `PackageName_ROOT` variable before we can get this in.

> I then tried to add a few python flags, as can be seen in the workflow text, but it didn't change the error.

This is an issue with the following lines in openvdb/python/CMakeLists.txt:

`find_package(Python ${MINIMUM_PYTHON_VERSION} ...)`

Unfortunately CMakes native `find_package(Python)` support treats the first version argument as an exact version for the corresponding major version. For example, `find_package(Python 2.7)` will allow you to use 2.7->2.X but not 3.0. Further, if you try to remove the `${MINIMUM_PYTHON_VERSION}` for Python3 support, boost *may* fail whilst finding boost_python.

This should be addressed by #503, I'm just waiting on some other updates so that #503 can be tested through our CI. For now I can recommend a couple of options to work around this:

1) As long as your CMake version >= 3.12, try adding `-DPython_ROOT=<location_to_py2>` to your CMake command. With both python 3.6.6 and 2.7.8 installed, I managed to point this to a python 2.7.8 location (the CMake docs say to use `Python_ROOT_DIR` but this did not work for me). Note however that you'll also need a compatible verison of boost_python for py2 for this to work.

2) Try building from the #503 branch. This should improve python3, numpy and boost support.

**Comment by nranthony** [comment]
Hi @Idclip , thanks again for your time.

I cloned [your instance of openvdb](https://github.com/Idclip/openvdb/branches) `git clone https://github.com/Idclip/openvdb.git ` and used `git switch cmake_numpy_improvements ` to use the branch you mention in https://github.com/AcademySoftwareFoundation/openvdb/pull/503 above.

I then ran:
```
cmake -G"Visual Studio 15 2017" -DCMAKE_CONFIGURATION_TYPES=%CONFIGURATION% -DCMAKE_INSTALL_PREFIX=%APPVEYOR_BUILD_FOLDER%\install -DCMAKE_TOOLCHAIN_FILE=C:\dev\vcpkg\scripts\buildsystems\vcpkg.cmake -DOPENVDB_ABI_VERSION_NUMBER=6 -DOPENVDB_BUILD_BINARIES=OFF -DOPENVDB_BUILD_PYTHON_MODULE=ON -DOPENVDB_BUILD_UNITTESTS=ON -DOPENEXR_ROOT=C:\dev\vcpkg\installed\x86-windows -DILMBASE_ROOT=C:\dev\vcpkg\installed\x86-windows -DTBB_ROOT=C:\dev\vcpkg\installed\x86-windows -DBLOSC_ROOT=C:\dev\vcpkg\installed\x86-windows -DUSE_BLOSC=ON -DCPPUNIT_ROOT=C:\dev\vcpkg\installed\x86-windows -DBOOST_ROOT=C:\dev\boost_1_71_0 -DBOOST_LIBRARYDIR=C:\dev\boost_1_71_0\lib -DPYTHON_ROOT=C:\Python27 ..
```
but alas received this error in the last steps:
```
-- ----------------------------------------------------
-- ------------ Configuring OpenVDBPython -------------
-- ----------------------------------------------------
CMake Error at C:/Program Files/CMake/share/cmake-3.14/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Python (missing: Python_EXECUTABLE Python_LIBRARY
  Interpreter Development) (found version "3.7.3")
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.14/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.14/Modules/FindPython.cmake:212 (find_package_handle_standard_args)
  C:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:256 (_find_package)
  openvdb/python/CMakeLists.txt:130 (find_package)
```
For completeness, I have Python 2.7.16 in folder `C:\Python27`, and 3.7.3 in my user Anaconda3 folder.

The complete cmd line output is here: 
[cmake cmd output_.txt](https://github.com/AcademySoftwareFoundation/openvdb/files/3644673/cmake.cmd.output_.txt)

From reading https://github.com/AcademySoftwareFoundation/openvdb/pull/503 and https://github.com/AcademySoftwareFoundation/openvdb/pull/504 it looks like you have some version/feature overlaps to figure out, which sounds arduous, but I'm happy to try any other suggestions you might have, and/or wait until there have been changes that will be things easier.  No point banging head on the wall if the wall is going to change soon.

Thanks
Neil

**Comment by nranthony** [comment]
Hi @Idclip , I hope the week wraps up well.
I was just wondering if you've had a chance to think about what I might try next, and/or if you feel it's worth just holding off for a little while?
Thanks
Neil

**Comment by Idclip** [comment]
Hi @nranthony,
Sorry for the delay - it looks like it's printing that it's found a python version `found version "3.7.3"` even though you're providing it a python root location to 2.7. So there's a couple of things you can try here (all on top of the #503 branch):

1) This branch should support python 3.X, so try simply removing the `DPYTHON_ROOT` variable
2) If that doesn't work, instead of `-DPYTHON_ROOT=C:\Python27` try `-DPython_ROOT=C:\Python27` 

If neither of these work then I suggests holding off for a bit whilst we get these improvements in. Something I should mention is that you can disable the python module with `OPENVDB_BUILD_PYTHON_MODULE=OFF` if you don't need it. It might be worth trying that anyway to make sure there are no other issues down the line!

**Comment by danrbailey** [comment]
Our recommendation is now to suggest using VCPKG_DEFAULT_TRIPLET=x64-windows and we've made a number of other changes to improve building OpenVDB on Windows. I'm going to close out this ticket, but if you're still encountering issues after picking up the latest changes, feel free to re-open.

**Comment by nranthony** [comment]
Hi Dan, thanks for following up.

I tried a fresh work through, but couldn't get VS2019 to build, and hoped you could help with the specifics of the above recommendation.  Note, I don't have `make` in place, and simply opened the .sln file created by cmake, set the build to be release and then right clicked on ALL BUILD and built from there.

I tried setting the system environment variable `VCPKG_DEFAULT_TRIPLET=x64-windows`, before running `vcpkg install boost zlib blosc openexr tbb`, but it still pulls in all x86 libraries, and the errors I get on building in VS2019 point to x86 being the trouble.

Am I setting it up correctly?  Should it be a user environment or system environment variable?  Or am I mixed up and this is a parameter for vcpkg?

Thanks in advance for your time.
Neil

**Comment by nranthony** [comment]
Sorry, my bad, I had a typo in my user environment variables, and stepped away for a little while, and then on returning to try adding to the system environment variables I then had two, one with a typo.  I corrected the typo, deleted the vcpkg folder and started over.  It then pulls the x64 libraries.

Alas, on the cmake step I run into errors...  I'll start a new thread.

Thanks
