### ISSUE TITLE
Python module build on Windows

### ISSUE THREAD

**Issue by BohusBrecka** [AcademySoftwareFoundation/openvdb#527]
Hello,

I've been trying to build OpenVDB Python module using Microsoft C++ compiler. I've resolved minor issues (compile error at std::min by using #define NOMINMAX), but I am stuck with this:

...\openvdb\python\pyOpenVDBModule.cc(835): error C2375: 'initpyopenvdb': redefinition; different linkage
...\openvdb\src\v6.1.0-405cd4b264\openvdb\python\pyOpenVDBModule.cc(832): note: see declaration of 'initpyopenvdb'

Does anyone have an experience with this? 

I've managed to get rid of the error by commenting out lines 826 to 832 and rewriting the line 835 to: extern "C" void initpyopenvdb()
It compiled but when I tried to import the dll (pyd) in Python I got "ImportError: dynamic module does not define init function (initpyopenvdb)"

Also I tried the same thing but on line 835 I put: 
BOOST_PYTHON_MODULE(pyopenvdb)
It also compiled but after importing in Python there is error "ImportError: DLL load failed: The specified module could not be found"

My compiler version is 19.16.27032.1
Python 2.7 (the module did not work with Python 3)
I don't know what else could be relevant.

Thank you.

**Comment by pcucka** [comment]
Maybe try replacing
```
#ifdef DWA_OPENVDB
#define PY_OPENVDB_MODULE_NAME  _openvdb
extern "C" { void init_openvdb(); }
#else
#define PY_OPENVDB_MODULE_NAME  pyopenvdb
extern "C" { void initpyopenvdb(); }
#endif

BOOST_PYTHON_MODULE(PY_OPENVDB_MODULE_NAME)
```
with just
```
BOOST_PYTHON_MODULE(pyopenvdb)
```

Those `extern "C"` function prototypes were added some time ago to suppress missing prototype warnings from Clang, but perhaps they're not needed anymore.

**Comment by Idclip** [comment]
Hi @BohusBrecka, any luck with the above?

**Comment by BohusBrecka** [comment]
Hi,

finally I've solved that by modifying the scripts to use Python3, then it worked fine. 

The newer versions of OpenVDB use Python3 as default, so I guess this is not a problem anymore, I was just using version 6.1.0 because it was available on vcpkg. 

Regarding @pcucka response - I've tried many things and removing the defines was one of my first shots. Sorry for not responding sooner.

Bohus Brecka

**Comment by e4lam** [comment]
In trying to build the openvdb python module for vcpkg, I also ran into  this issue.

I'm not sure why we need to pre-declare it in the first place because this is what `BOOST_PYTHON_MODULE()` is meant to do. This has not been required as far as I can tell since at least [Boost 1.66](https://www.boost.org/doc/libs/1_66_0/libs/python/doc/html/reference/high_level_components/boost_python_module_hpp.html#high_level_components.boost_python_module_hpp.introduction).

If someone tests this out on Linux, I propose that we should just remove the extraneous `extern "C" { ... }` declarations at [line 807](https://github.com/AcademySoftwareFoundation/openvdb/blob/5f9ff0152952211a326a41d258a0b16263b97502/openvdb/python/pyOpenVDBModule.cc#L807) and [line 810](https://github.com/AcademySoftwareFoundation/openvdb/blob/5f9ff0152952211a326a41d258a0b16263b97502/openvdb/python/pyOpenVDBModule.cc#L810).

I encountered while trying to help out issue #603

**Comment by tsvilans** [comment]
Hi, I am also having problems with the Python module: using vcpkg and CMake, I can get all the dependencies for OpenVDB and build it with the Python module enabled. `pyopenvdb.pyd` is created.

However, when testing the module with `import pyopenvdb` I get an error `ImportError: DLL load failed while importing pyopenvdb: The specified procedure could not be found.`

I've been careful to keep a consistent Python version throughout, so I don't think it's a Python version problem. Either way, I've made sure to use the same Python version as the one downloaded by vcpkg for the Boost dependencies.

Running the Dependancy Walker on the module shows a long list of missing export functions in `openvdb.dll`.

Any ideas?

**Comment by Idclip** [comment]
Going to close this one as no issues have been reported since
