### ISSUE TITLE
possible to show voxel colors in vdb_view?

### ISSUE THREAD

**Issue by amir90** [AcademySoftwareFoundation/openvdb#608]
Hi,

I am currently using vdb_view to render the voxels to test my output.
Is there any way to make it show color based on voxel metadata?

**Comment by Idclip** [comment]
Hello @amir90 - can you elaborate on what you mean by voxel metadata? What kind of VDBs are you trying to display? Note that 3 component vector valued VDBs can display their components as line colours based off their magnitude relative to the maximum value in the VDB, but these colours are currently hard coded.

**Comment by amir90** [comment]
Hi,
 By voxel metadata, I mean the RGB values of the voxel, for each active voxel. 
Maybe its a bit of an overkill, but in the meanwhile, I used Houdini for visualization, which worked for me. I will try your suggested a 3-component vector valued VDB and see what I get.
Thank you.

**Comment by Idclip** [comment]
Okay understood. There are two main modes that the `vdb_view` binary has for drawing VDB volumes (excluding VDB Points). 

---------------

For scalar (`int`, `float`, `double` etc) volumes, `vdb_view` will draw voxels with the following colours:

If the Grid is a level set:
- Red:   Outside the level set (the value is greater than zero)
- White: Inside the level set (the value is less than zero)

Otherwise, the minimum and maximum values are used to normalize/remap all values within the VDB:
 - Green->Red: Negative values are interpolated between green (closest to zero) and red (furthest from zero)
 - Yellow->Blue: Positive values are interpolated between blue (closest to zero) to yellow (further from zero) 

---------------

For `vec3f` or `vec3d` grids, xyz values are displayed as GL lines for each voxel where:

Each voxel has the magnitude of its vector remapped in terms of the grids minimum and maximum values:
 - Blue->Red: Closest to zero values in blue , higher values in Red. 

---------------

These are the only value interpretation modes the `vdb_view` binary currently has as far as colouring the voxels. You'll find this code in the `ActiveScalarValuesOp` and `ActiveVectorValuesOp` operators in `openvdb/viewer/RenderModules.cc`. You might be able to tweak this to your needs - otherwise if you need anything more custom, using Houdini is your best bet.

**Comment by Idclip** [comment]
@amir90 I'm going to close out this issue, but please feel free to re-open if you continue to have questions
