### ISSUE TITLE
Allow OpenVDB to build without OpenEXR/Half.h

### ISSUE THREAD

**Issue by BenFrantzDale** [AcademySoftwareFoundation/openvdb#638]
As far as I can tell, the only reason the base OpenVDB requires OpenEXR is to allow loading and saving half-precision data. As one who has no interest in that feature, it's annoying to set up OpenEXR as a dependency for what feels like a niche feature.

If there's interest in this, I can make a PR. The approach I took is to replace all the `bool`s denoting half-precision reading and writing with
```
// Type-safe flag for reading/writing as half.
enum class StoredAsHalf {
    no,
#ifdef OPENVDB_WITH_OPENEXR_HALF
    yes
#endif
};
```
that way if compiled without Half, there's no way to specify that you'd like to read/write halfs. It has the added advantage of using an enum rather than a `bool`, for added type safety.

Is this of interest?

**Comment by danrbailey** [comment]
What you're proposing in general sounds good to me. However, it's probably quite a challenging change to make in practice as we use the half data type _a lot_ in the codebase.

A few specifics about such an implementation:

* It should follow the convention for enabling/disabling other features through CMake such as USE_EXR (https://github.com/AcademySoftwareFoundation/openvdb/blob/develop/CMakeLists.txt#L85)
* It should default to ON to avoid changing existing behavior when building the library
* Attempts to read a Grid that has been written as half will now fail - this should be handled in the same vein as attempting to read a Grid with Blosc compression with a library that has been built without Blosc compression enabled (https://github.com/AcademySoftwareFoundation/openvdb/blob/develop/openvdb/io/Compression.cc#L167)
* Logic handling half not being available should be introduced in as few places as possible, here's one example (https://github.com/AcademySoftwareFoundation/openvdb/blob/develop/openvdb/io/Compression.h#L623)

I'd suggest starting out by building the library and the unit tests, then commenting out this header file to get an idea of just how daunting this might prove to be:

https://github.com/AcademySoftwareFoundation/openvdb/blob/develop/openvdb/Types.h#L9

**Comment by Idclip** [comment]
+1 to this idea, though I agree with @danrbailey that it may require some serious thought to keep the API consistent. This is just a passing comment, but I've always wondered whether it'd be feasible to switch to a header only half implementation which would remove some of the dependency pains.

**Comment by BenFrantzDale** [comment]
Here's a proof of concept: https://github.com/AcademySoftwareFoundation/openvdb/pull/641

**Comment by danrbailey** [comment]
@BenFrantzDale - I'm not keen on the enum approach here as it's quite different to how we've handled this elsewhere. To give one specific example, it should be possible to mark a grid to be written out as half and then not actually write it without having an exception be thrown. Please read through my detailed description above of the kind of approach that would be more suitable for the project:

https://github.com/AcademySoftwareFoundation/openvdb/issues/638#issuecomment-589778854

I'm going to close out your PR, but more than happy to look over an implementation a little closer to what's been discussed here.

**Comment by BenFrantzDale** [comment]
Go ahead and close it.

As for "To give one specific example, it should be possible to mark a grid to be written out as half and then not actually write it without having an exception be thrown." I think you may not understand. With the approach I took, if you build without half, there is no way to mark a grid to be written out as half because the enum doesn't have a `StoredAsHalf::yes` value. So the API should be identical with and without half, provided you aren't using half, and exceptions should only be possible when reading files with half. (In contrast, had I left the flag as `bool`, there's a potential for a runtime error by asking to save as half (`toHalf = true`).) Does that make sense?

**Comment by danrbailey** [comment]
> Go ahead and close it.
> 
> As for "To give one specific example, it should be possible to mark a grid to be written out as half and then not actually write it without having an exception be thrown." I think you may not understand. With the approach I took, if you build without half, there is no way to mark a grid to be written out as half because the enum doesn't have a `StoredAsHalf::yes` value. So the API should be identical with and without half, provided you aren't using half, and exceptions should only be possible when reading files with half. (In contrast, had I left the flag as `bool`, there's a potential for a runtime error by asking to save as half (`toHalf = true`).) Does that make sense?

That is what I had understood. To be clear, we **want** the runtime error when writing if half is not available, rather than to silently switch the code path. Otherwise due to a mis-configured build, the user may not even be aware they are writing out VDBs that aren't using this feature.

Blosc compression is the best example of project convention here. If you explicitly request Blosc compression, when writing out VDB files (https://github.com/AcademySoftwareFoundation/openvdb/blob/develop/openvdb/io/Archive.cc#L277), you'll get an error thrown here (https://github.com/AcademySoftwareFoundation/openvdb/blob/develop/openvdb/io/Compression.cc#L167).

**Comment by BenFrantzDale** [comment]
OK, I can have it do what Blosc does there. If I understand, your concern is that even if `StoredAsHalf::yes` isn't available in one compilation unit, someone could, e.g., pass `static_cast<StoredAsHalf>(1)` in and what I've got now would silently do nothing, correct?

**Comment by BenFrantzDale** [comment]
OK, does this address your concerns?: https://github.com/AcademySoftwareFoundation/openvdb/compare/develop...BenFrantzDale:hack/no-half?expand=1

**Comment by danrbailey** [comment]
It's better, but you still seem to be trying to use your `StoredAsHalf` enum which I'll reiterate is _not_ required. You should be able to isolate most of the changes to `openvdb/io/Compression.h`.

**Comment by BenFrantzDale** [comment]
OK. Again, my thought there is that it's better to tweak the API so that it at compile time it is impossible to ask for `half` storage when it's not available. But if you'd prefer to keep the API untouched and fall back to just runtime errors, I can do that.

**Comment by BenFrantzDale** [comment]
So like this?: https://github.com/AcademySoftwareFoundation/openvdb/compare/master...BenFrantzDale:hack/no-half-with-bool?expand=1

**Comment by danrbailey** [comment]
@BenFrantzDale - much closer, thanks.

I'll mention a few points here, then suggest you squash the commits and re-submit as a PR and we can continue noodling until it's ready.

For the purposes of OpenVDB, half only means OpenEXR half, so no need to disambiguate them. As a result, I'd suggest we rename "OPENVDB_USE_OPENEXR_HALF" => "OPENVDB_USE_HALF" in the code for simplicity (likewise in the CMake "USE_OPENEXR_HALF" should be "USE_HALF").

Also, I suggest we rename the error message from "Half-float is not supported" => "OpenVDB has been compiled without Half support". Otherwise it sounds like the library itself does not support half, which is not the case. (Admittedly the Blosc error could be less ambiguous).

An empty grid with "saving float as half" mode enabled should still read or write successfully, so no need to handle errors in places such as `GridBase::saveFloatAsHalf()`.

Finally, it's not valid to just remove "IlmBase::Half" from OPENVDB_CORE_DEPENDENT_LIBS, it'll have to be handled for cases where building with Half is enabled/disabled. Related - if USE_EXR is enabled, USE_HALF should always be enabled.

A few comments regarding how this is implemented in AttributeArray too, but I can add these through code review.

**Comment by BenFrantzDale** [comment]
Great. Will do.

**Comment by BenFrantzDale** [comment]
https://github.com/AcademySoftwareFoundation/openvdb/pull/651

**Comment by Idclip** [comment]
This work has now been merged and will be available in the next release - VDB will come with it's own implementation of half floating point types which it will use by default; alternatively, the implementation of half from ilmbase can still be switch to with a new CMake variable `USE_IMATH_HALF` (defaults to OFF). The `USE_EXR` flag has been removed and all exr deps have been removed as optional libs from the core lib (they are only needed for the `vdb_render` binary).
