### ISSUE TITLE
Build 64 bit on Windows

### ISSUE THREAD

**Issue by Megidd** [AcademySoftwareFoundation/openvdb#855]
I built OpenVDB on Windows and it went smoothly:

https://github.com/AcademySoftwareFoundation/openvdb#windows

But the OpenVDB is installed inside `Program Files (x86)` which implies it is 32 bit version not 64 bit:

```batch
>cmake --build . --parallel 4 --config Release --target install

...

  -- Installing: C:/Program Files (x86)/OpenVDB/lib/libopenvdb.lib
  -- Installing: C:/Program Files (x86)/OpenVDB/lib/openvdb.lib
  -- Installing: C:/Program Files (x86)/OpenVDB/bin/openvdb.dll

...

```

How can I install 64 bit version? Did I miss something? Thanks!

**Comment by Idclip** [comment]
Hello @Megidd,

I'm testing with VS 15 2017 and can replicate this too - pretty strange, I've managed to resolve it by specifying the arch requirement in the VS target generator rather than directly with the architecture argument -A. i.e instead of 

```
cmake  -A x64 ..
```

do

```
cmake  -G Visual Studio 15 2017 Win64 ..
```

Where your argument to -G is your desired VS generator (you can see all available options and the current default at the bottom of the output from  `cmake --help`) followed by `Win64`. Note that for VS 16 this option has been removed (and you have to use -A) so I hope this works for you. 

My understanding from https://cmake.org/cmake/help/git-stage/generator/Visual%20Studio%2015%202017.html is that these should be equal... but I'm getting `Program Files` correctly now.

**Comment by Idclip** [comment]
And, just to clarify, even though it's incorrectly installing to `Program Files (x86)`, it should be building the 64bit version with either `-A x64` or `-G blah Win64`

**Comment by Megidd** [comment]
I can confirm that the binary is actually `64 bit`:

![2020-10-25 17_10_37-Window](https://user-images.githubusercontent.com/17475482/97108842-5851a680-16e5-11eb-8269-7f1ca2bd9632.png)
